"""Render the per-product feature-council runtime bundle.

For an :class:`~dsf.instance.spec.InstanceManifest`, write a
``compose.orchestrator.yml`` + ``.env.orchestrator`` pair into
``config/instances/<product>.runtime/``. The env file scopes the runtime to the
product (``DSF_PRODUCT``) and carries the Azure backing-service endpoints captured
in the deployment outputs. Secrets (bearer tokens, GitHub tokens) are NOT
rendered — they are injected at runtime from Key Vault via the homelab service
principal (ADR 0002: the homelab authenticates with an Entra SP, not Managed
Identity, which only works inside Azure).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dsf.instance.spec import InstanceManifest, instances_dir

#: Mapping of Bicep deployment output keys -> the env var names the runtime reads
#: (kept symmetric with :meth:`dsf.container.AzureRuntimeSettings.from_env`).
_ENDPOINT_MAP: tuple[tuple[str, str], ...] = (
    ("AZURE_APPCONFIG_ENDPOINT", "appConfigEndpoint"),
    ("AZURE_KEYVAULT_URI", "keyVaultUri"),
    ("APPLICATIONINSIGHTS_CONNECTION_STRING", "appInsightsConnectionString"),
    ("AZURE_COSMOS_ENDPOINT", "cosmosEndpoint"),
)


@dataclass(frozen=True)
class RuntimeBundle:
    """Paths to the rendered runtime files for one product."""

    runtime_dir: Path
    compose_path: Path
    env_path: Path


def runtime_dir(product: str, repo_root: Path | None = None) -> Path:
    """Directory holding a product's generated runtime bundle."""
    return instances_dir(repo_root) / f"{product}.runtime"


def _render_env(product: str, outputs: dict[str, str]) -> str:
    lines = [
        "# .env.orchestrator — GENERATED by dsf (render_runtime_bundle). Do not edit.",
        "# Endpoints come from the product's Azure deployment outputs. Secrets are",
        "# injected at runtime (Key Vault via the homelab service principal, ADR 0002),",
        "# never rendered here.",
        "DSF_MODE=azure",
        f"DSF_PRODUCT={product}",
    ]
    lines.extend(f"{var}={outputs.get(key, '')}" for var, key in _ENDPOINT_MAP)
    return "\n".join(lines) + "\n"


def _render_compose(product: str, resource_group: str) -> str:
    return (
        "# compose.orchestrator.yml — GENERATED by dsf (render_runtime_bundle).\n"
        f"# Feature-council runtime for product '{product}'. Backing services live\n"
        f"# in Azure RG '{resource_group}' and are reached OUTBOUND (see ADR 0002).\n"
        "#\n"
        "# Usage (homelab):\n"
        "#   docker compose -f compose.orchestrator.yml --env-file .env.orchestrator up -d\n"
        "services:\n"
        "  orchestrator:\n"
        "    # Built from the orchestrator runtime image. Build context is the REPO\n"
        "    # ROOT so `pip install .` resolves the dsf package.\n"
        "    build:\n"
        "      context: ../../..\n"
        "      dockerfile: src/dsf/runtime/Dockerfile\n"
        "    image: ${DSF_RUNTIME_IMAGE:-dsf/runtime:local}\n"
        f"    container_name: dsf-orchestrator-{product}\n"
        "    restart: unless-stopped\n"
        "    env_file:\n"
        "      - .env.orchestrator\n"
        "    networks:\n"
        "      - dsf\n"
        "networks:\n"
        "  dsf:\n"
        "    driver: bridge\n"
    )


def render_runtime_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> RuntimeBundle:
    """Render ``compose.orchestrator.yml`` + ``.env.orchestrator`` for ``manifest``.

    Tolerates a manifest with no Azure outputs yet (endpoints render blank).
    """
    product = manifest.spec.product
    outputs = manifest.azure.outputs if manifest.azure else {}
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    env_path = rdir / ".env.orchestrator"
    compose_path = rdir / "compose.orchestrator.yml"
    env_path.write_text(_render_env(product, outputs), encoding="utf-8")
    compose_path.write_text(
        _render_compose(product, manifest.spec.resource_group()), encoding="utf-8"
    )
    return RuntimeBundle(runtime_dir=rdir, compose_path=compose_path, env_path=env_path)


__all__ = ["RuntimeBundle", "render_runtime_bundle", "runtime_dir"]
