"""Render the per-product feature-council runtime bundle.

For an :class:`~dsf.instance.spec.InstanceManifest`, write a
``containerapp.yaml`` + ``.env.orchestrator`` pair into
``config/instances/<product>.runtime/``. The env file scopes the runtime to the
product (``DSF_PRODUCT``) and carries the Azure backing-service endpoints captured
in the deployment outputs. Secrets (bearer tokens, GitHub tokens) are NOT
rendered — the runtime reads them from Key Vault using its Azure Container Apps
user-assigned managed identity (ADR 0004).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dsf.instance.spec import InstanceManifest, instances_dir

#: Mapping of Bicep deployment output keys -> the env var names the runtime reads
#: (kept symmetric with :meth:`dsf.container.AzureRuntimeSettings.from_env`).
_ENDPOINT_MAP: tuple[tuple[str, str], ...] = (
    ("AZURE_APPCONFIG_ENDPOINT", "appConfigEndpoint"),
    ("AZURE_KEYVAULT_URI", "keyVaultUri"),
    ("APPLICATIONINSIGHTS_CONNECTION_STRING", "appInsightsConnectionString"),
    ("AZURE_COSMOS_ENDPOINT", "cosmosEndpoint"),
)


@dataclass(frozen=True)
class RuntimeBundle:
    """Paths to the rendered runtime files for one product."""

    runtime_dir: Path
    app_config_path: Path
    env_path: Path


def runtime_dir(product: str, repo_root: Path | None = None) -> Path:
    """Directory holding a product's generated runtime bundle."""
    return instances_dir(repo_root) / f"{product}.runtime"


def _render_env(product: str, outputs: dict[str, str]) -> str:
    lines = [
        "# .env.orchestrator — GENERATED by dsf (render_runtime_bundle). Do not edit.",
        "# Endpoints come from the product's Azure deployment outputs. Secrets are",
        "# read at runtime from Key Vault via the ACA managed identity (ADR 0004),",
        "# never rendered here.",
        "DSF_MODE=azure",
        f"DSF_PRODUCT={product}",
    ]
    lines.extend(f"{var}={outputs.get(key, '')}" for var, key in _ENDPOINT_MAP)
    return "\n".join(lines) + "\n"


def _render_app_config(product: str, resource_group: str, image: str) -> str:
    return (
        "# containerapp.yaml — GENERATED by dsf (render_runtime_bundle).\n"
        f"# App: dsf-orchestrator-{product}\n"
        f"# Feature-council orchestrator runtime for product '{product}', hosted on\n"
        f"# Azure Container Apps in RG '{resource_group}' (ADR 0004). Identity, env, and\n"
        "# scale are provisioned by infra/main.bicep; this is the declarative record\n"
        "# reconciled by `az containerapp update` during deploy_council.\n"
        "properties:\n"
        "  configuration:\n"
        "    activeRevisionsMode: Single\n"
        "  template:\n"
        "    containers:\n"
        "      - name: orchestrator\n"
        f"        image: {image}\n"
        "        env:\n"
        "          - name: DSF_MODE\n"
        "            value: azure\n"
        "          - name: DSF_PRODUCT\n"
        f"            value: {product}\n"
        "    scale:\n"
        "      minReplicas: 1\n"
        "      maxReplicas: 1\n"
    )


def render_runtime_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> RuntimeBundle:
    """Render ``containerapp.yaml`` + ``.env.orchestrator`` for ``manifest``.

    Tolerates a manifest with no Azure outputs yet (endpoints render blank).
    """
    product = manifest.spec.product
    outputs = manifest.azure.outputs if manifest.azure else {}
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    env_path = rdir / ".env.orchestrator"
    app_config_path = rdir / "containerapp.yaml"
    env_path.write_text(_render_env(product, outputs), encoding="utf-8")
    app_config_path.write_text(
        _render_app_config(
            product, manifest.spec.resource_group(), manifest.spec.runtime_image
        ),
        encoding="utf-8",
    )
    return RuntimeBundle(
        runtime_dir=rdir, app_config_path=app_config_path, env_path=env_path
    )


__all__ = ["RuntimeBundle", "render_runtime_bundle", "runtime_dir"]
