"""Render the per-product feature-council runtime bundle.

For an :class:`~dsf.instance.spec.InstanceManifest`, write a
``containerapp.yaml`` + ``.env.orchestrator`` pair into
``config/instances/<product>.runtime/``. The env file scopes the runtime to the
product (``DSF_PRODUCT``) and carries the Azure backing-service endpoints captured
in the deployment outputs. Secrets (bearer tokens, GitHub tokens) are NOT
rendered — the runtime reads them from Key Vault using its Azure Container Apps
user-assigned managed identity (ADR 0004).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dsf.instance.spec import InstanceManifest, instances_dir

#: Mapping of Bicep deployment output keys -> the env var names the runtime reads
#: (kept symmetric with :meth:`dsf.container.AzureRuntimeSettings.from_env`).
_ENDPOINT_MAP: tuple[tuple[str, str], ...] = (
    ("AZURE_APPCONFIG_ENDPOINT", "appConfigEndpoint"),
    ("AZURE_KEYVAULT_URI", "keyVaultUri"),
    ("APPLICATIONINSIGHTS_CONNECTION_STRING", "appInsightsConnectionString"),
    ("AZURE_COSMOS_ENDPOINT", "cosmosEndpoint"),
)


@dataclass(frozen=True)
class RuntimeBundle:
    """Paths to the rendered runtime files for one product."""

    runtime_dir: Path
    app_config_path: Path
    env_path: Path


@dataclass(frozen=True)
class SreBundle:
    """Path to the rendered SRE container-app descriptor for one product."""

    runtime_dir: Path
    app_config_path: Path


def runtime_dir(product: str, repo_root: Path | None = None) -> Path:
    """Directory holding a product's generated runtime bundle."""
    return instances_dir(repo_root) / f"{product}.runtime"


def _render_env(product: str, outputs: dict[str, str]) -> str:
    lines = [
        "# .env.orchestrator — GENERATED by dsf (render_runtime_bundle). Do not edit.",
        "# Endpoints come from the product's Azure deployment outputs. Secrets are",
        "# read at runtime from Key Vault via the ACA managed identity (ADR 0004),",
        "# never rendered here.",
        "DSF_MODE=azure",
        f"DSF_PRODUCT={product}",
    ]
    lines.extend(f"{var}={outputs.get(key, '')}" for var, key in _ENDPOINT_MAP)
    return "\n".join(lines) + "\n"


def _render_containerapp(*, app: str, container: str, product: str, image: str, role: str) -> str:
    """Render a single Azure Container Apps descriptor.

    Shared by the feature-council (``deploy_council``) and SRE (``deploy_sre``)
    runtimes. Identity, env, and scale are provisioned by ``infra/main.bicep``;
    this is the declarative record reconciled by ``az containerapp update``.
    """
    return (
        "# containerapp.yaml — GENERATED by dsf (render_runtime_bundle).\n"
        f"# App: {app}\n"
        f"# {role} for product '{product}', hosted on Azure Container Apps (ADR 0004).\n"
        "properties:\n"
        "  configuration:\n"
        "    activeRevisionsMode: Single\n"
        "  template:\n"
        "    containers:\n"
        f"      - name: {container}\n"
        f"        image: {image}\n"
        "        env:\n"
        "          - name: DSF_MODE\n"
        "            value: azure\n"
        "          - name: DSF_PRODUCT\n"
        f"            value: {product}\n"
        "    scale:\n"
        "      minReplicas: 1\n"
        "      maxReplicas: 1\n"
    )


def render_runtime_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> RuntimeBundle:
    """Render ``containerapp.yaml`` + ``.env.orchestrator`` for ``manifest``.

    Tolerates a manifest with no Azure outputs yet (endpoints render blank).
    """
    product = manifest.spec.product
    outputs = manifest.azure.outputs if manifest.azure else {}
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    env_path = rdir / ".env.orchestrator"
    app_config_path = rdir / "containerapp.yaml"
    env_path.write_text(_render_env(product, outputs), encoding="utf-8")
    app_config_path.write_text(
        _render_containerapp(
            app=f"dsf-orchestrator-{product}",
            container="orchestrator",
            product=product,
            image=manifest.spec.runtime_image,
            role="Feature-council orchestrator runtime",
        ),
        encoding="utf-8",
    )
    return RuntimeBundle(
        runtime_dir=rdir, app_config_path=app_config_path, env_path=env_path
    )


def render_sre_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> SreBundle:
    """Render ``sre.containerapp.yaml`` for the product's SRE agent runtime.

    Mirrors :func:`render_runtime_bundle` but for the ``dsf-sre-<product>``
    container app. The SRE agent reads the same Azure backing-service endpoints
    from Key Vault/App Configuration at runtime via the ACA managed identity
    (ADR 0004), so no separate env file is rendered.
    """
    product = manifest.spec.product
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    app_config_path = rdir / "sre.containerapp.yaml"
    app_config_path.write_text(
        _render_containerapp(
            app=f"dsf-sre-{product}",
            container="sre",
            product=product,
            image=manifest.spec.runtime_image,
            role="SRE agent runtime",
        ),
        encoding="utf-8",
    )
    return SreBundle(runtime_dir=rdir, app_config_path=app_config_path)


__all__ = [
    "RuntimeBundle",
    "SreBundle",
    "render_runtime_bundle",
    "render_sre_bundle",
    "runtime_dir",
]
