<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dsf-runtime</AssemblyName>
    <RootNamespace>Dsf.Runtime</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dsf.Core\Dsf.Core.csproj" />
    <ProjectReference Include="..\Dsf.FeatureCouncil\Dsf.FeatureCouncil.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Azure.Data.AppConfiguration" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dsf.Runtime.Tests" />
  </ItemGroup>

</Project>
