"""Render the per-product feature-council runtime bundle.

For an :class:`~dsf.instance.spec.InstanceManifest`, write a
``containerapp.yaml`` + ``.env.orchestrator`` pair into
``config/instances/<product>.runtime/``. The env file scopes the runtime to the
product (``DSF_PRODUCT``) and carries the Azure backing-service endpoints captured
in the deployment outputs. Secrets (bearer tokens, GitHub tokens) are NOT
rendered — the runtime reads them from Key Vault using its Azure Container Apps
user-assigned managed identity (ADR 0004).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dsf.config.registry import Product, register_product, unregister_product
from dsf.contracts.handoff import HANDOFF_LABEL, INCIDENT_LABEL
from dsf.instance.spec import (
    InstanceManifest,
    InstanceSpec,
    _default_repo_root,
    instances_dir,
)

#: Mapping of Bicep deployment output keys -> the env var names the runtime reads
#: (kept symmetric with :meth:`dsf.container.AzureRuntimeSettings.from_env`).
_ENDPOINT_MAP: tuple[tuple[str, str], ...] = (
    ("AZURE_APPCONFIG_ENDPOINT", "appConfigEndpoint"),
    ("AZURE_KEYVAULT_URI", "keyVaultUri"),
    ("APPLICATIONINSIGHTS_CONNECTION_STRING", "appInsightsConnectionString"),
    ("AZURE_COSMOS_ENDPOINT", "cosmosEndpoint"),
    ("AZURE_OPENAI_ENDPOINT", "openaiEndpoint"),
    ("AZURE_OPENAI_DEPLOYMENT", "openaiDeployment"),
    ("AZURE_OPENAI_EMBEDDING_DEPLOYMENT", "openaiEmbeddingDeployment"),
)


@dataclass(frozen=True)
class RuntimeBundle:
    """Paths to the rendered runtime files for one product."""

    runtime_dir: Path
    app_config_path: Path
    env_path: Path


@dataclass(frozen=True)
class SreSummary:
    """Path to the rendered Azure SRE Agent post-deploy summary for one product."""

    runtime_dir: Path
    summary_path: Path


def runtime_dir(product: str, repo_root: Path | None = None) -> Path:
    """Directory holding a product's generated runtime bundle."""
    return instances_dir(repo_root) / f"{product}.runtime"


def _render_env(product: str, outputs: dict[str, str]) -> str:
    lines = [
        "# .env.orchestrator — GENERATED by dsf (render_runtime_bundle). Do not edit.",
        "# Endpoints come from the product's Azure deployment outputs. Secrets are",
        "# read at runtime from Key Vault via the ACA managed identity (ADR 0004),",
        "# never rendered here.",
        f"DSF_PRODUCT={product}",
    ]
    lines.extend(f"{var}={outputs.get(key, '')}" for var, key in _ENDPOINT_MAP)
    return "\n".join(lines) + "\n"


def _render_containerapp(*, app: str, container: str, product: str, image: str, role: str) -> str:
    """Render a single Azure Container Apps descriptor.

    Renders the feature-council (``deploy_council``) runtime. Identity, env, and
    scale are provisioned by ``infra/main.bicep``; this is the declarative record
    reconciled by ``az containerapp update``.
    """
    return (
        "# containerapp.yaml — GENERATED by dsf (render_runtime_bundle).\n"
        f"# App: {app}\n"
        f"# {role} for product '{product}', hosted on Azure Container Apps (ADR 0004).\n"
        "properties:\n"
        "  configuration:\n"
        "    activeRevisionsMode: Single\n"
        "  template:\n"
        "    containers:\n"
        f"      - name: {container}\n"
        f"        image: {image}\n"
        "        env:\n"
        "          - name: DSF_PRODUCT\n"
        f"            value: {product}\n"
        "    scale:\n"
        "      minReplicas: 1\n"
        "      maxReplicas: 1\n"
    )


def render_runtime_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> RuntimeBundle:
    """Render ``containerapp.yaml`` + ``.env.orchestrator`` for ``manifest``.

    Tolerates a manifest with no Azure outputs yet (endpoints render blank).
    """
    product = manifest.spec.product
    outputs = manifest.azure.outputs if manifest.azure else {}
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    env_path = rdir / ".env.orchestrator"
    app_config_path = rdir / "containerapp.yaml"
    env_path.write_text(_render_env(product, outputs), encoding="utf-8")
    app_config_path.write_text(
        _render_containerapp(
            app=f"dsf-orchestrator-{product}",
            container="orchestrator",
            product=product,
            image=manifest.spec.runtime_image,
            role="Feature-council orchestrator runtime",
        ),
        encoding="utf-8",
    )
    return RuntimeBundle(
        runtime_dir=rdir, app_config_path=app_config_path, env_path=env_path
    )


def _render_sre_summary_md(
    *, product: str, agent_name: str, monitored_rgs: list[str], repo: str
) -> str:
    rgs_list = "\n".join(f"- `{rg}`" for rg in monitored_rgs)
    return (
        f"# Azure SRE Agent — {product}\n\n"
        f"GENERATED by dsf (render_sre_summary). Do not edit.\n\n"
        f"The SRE Agent for this product has been provisioned by `dsf new`.\n\n"
        "## What was created\n\n"
        f"- Agent: `{agent_name}`\n"
        f"- Product repo connected: `{repo}`\n"
        f"- Monitored resource groups:\n{rgs_list}\n\n"
        "## Verify (one-time)\n\n"
        f"Run `az deployment sub show -n dsf-sre-{product}` to confirm the deployment\n"
        "completed cleanly. Check the agent portal at <https://sre.azure.com> to see\n"
        "the agent is active and the repo connection shows green.\n\n"
        "## Labels (keep these)\n\n"
        f"The `{HANDOFF_LABEL}` label routes SRE-filed issues into the creation phase\n"
        "(the Copilot Coding Agent). Both labels are created by the `create_labels` step.\n\n"
        f"Also stamp incident issues with `{INCIDENT_LABEL}`. The feature council's\n"
        "incidents source pulls issues carrying it, so the council learns from\n"
        "resolved incidents alongside production telemetry.\n"
    )


def render_sre_summary(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> SreSummary:
    """Render ``sre-agent.md`` -- a short post-deploy summary for one product.

    Writes what was provisioned (agent name, monitored RGs, repo) plus the
    one-time verify note and label reminder. No interactive steps.
    """
    spec = manifest.spec
    product = spec.product
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    summary_path = rdir / "sre-agent.md"
    summary_path.write_text(
        _render_sre_summary_md(
            product=product,
            agent_name=spec.sre_agent_name(),
            monitored_rgs=spec.monitored_rgs(),
            repo=spec.github_repo(),
        ),
        encoding="utf-8",
    )
    return SreSummary(runtime_dir=rdir, summary_path=summary_path)


def _product_from_spec(spec: InstanceSpec) -> Product:
    """Map an instance spec to its runtime :class:`Product` registry entry.

    Observability scopes (``sentry_projects`` / ``grafana_dashboards``) are left
    empty here — they are filled in during observability onboarding —, while
    ``foundryiq_scope`` and ``azure_monitor_scope`` default to the product key
    (the live Application Insights id is filled in during observability
    onboarding).
    """
    return Product(
        key=spec.product,
        github_repo=spec.github_repo(),
        label_taxonomy=spec.label_taxonomy,
        confidence_threshold=spec.confidence_threshold,
        foundryiq_scope=spec.product,
        azure_monitor_scope=spec.product,
    )


def render_product_registration(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> Path:
    """Register the product into ``config/products.json`` (the routing registry).

    Derives a :class:`~dsf.config.registry.Product` from the instance spec and
    upserts it idempotently, so S1 scoping and S6 routing can resolve the product
    to its repo as a byproduct of ``dsf new``. Pure local file IO (no network),
    so it runs in both dry-run and execute. Returns the registry path.
    """
    products_json = (repo_root or _default_repo_root()) / "config" / "products.json"
    return register_product(_product_from_spec(manifest.spec), path=products_json)


def render_product_unregistration(product: str, *, repo_root: Path | None = None) -> Path:
    """Unregister ``product`` from ``config/products.json`` (idempotent)."""
    products_json = (repo_root or _default_repo_root()) / "config" / "products.json"
    return unregister_product(product, path=products_json)


__all__ = [
    "RuntimeBundle",
    "SreSummary",
    "render_product_registration",
    "render_product_unregistration",
    "render_runtime_bundle",
    "render_sre_summary",
    "runtime_dir",
]
