"""Render the per-product feature-council runtime bundle.

For an :class:`~dsf.instance.spec.InstanceManifest`, write a
``containerapp.yaml`` + ``.env.orchestrator`` pair into
``config/instances/<product>.runtime/``. The env file scopes the runtime to the
product (``DSF_PRODUCT``) and carries the Azure backing-service endpoints captured
in the deployment outputs. Secrets (bearer tokens, GitHub tokens) are NOT
rendered — the runtime reads them from Key Vault using its Azure Container Apps
user-assigned managed identity (ADR 0004).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dsf.config.registry import Product, register_product
from dsf.contracts.handoff import HANDOFF_LABEL, INCIDENT_LABEL
from dsf.instance.spec import (
    InstanceManifest,
    InstanceSpec,
    _default_repo_root,
    instances_dir,
)

#: Mapping of Bicep deployment output keys -> the env var names the runtime reads
#: (kept symmetric with :meth:`dsf.container.AzureRuntimeSettings.from_env`).
_ENDPOINT_MAP: tuple[tuple[str, str], ...] = (
    ("AZURE_APPCONFIG_ENDPOINT", "appConfigEndpoint"),
    ("AZURE_KEYVAULT_URI", "keyVaultUri"),
    ("APPLICATIONINSIGHTS_CONNECTION_STRING", "appInsightsConnectionString"),
    ("AZURE_COSMOS_ENDPOINT", "cosmosEndpoint"),
)


@dataclass(frozen=True)
class RuntimeBundle:
    """Paths to the rendered runtime files for one product."""

    runtime_dir: Path
    app_config_path: Path
    env_path: Path


@dataclass(frozen=True)
class SreOnboarding:
    """Path to the rendered Azure SRE Agent onboarding runbook for one product."""

    runtime_dir: Path
    onboarding_path: Path


def runtime_dir(product: str, repo_root: Path | None = None) -> Path:
    """Directory holding a product's generated runtime bundle."""
    return instances_dir(repo_root) / f"{product}.runtime"


def _render_env(product: str, outputs: dict[str, str]) -> str:
    lines = [
        "# .env.orchestrator — GENERATED by dsf (render_runtime_bundle). Do not edit.",
        "# Endpoints come from the product's Azure deployment outputs. Secrets are",
        "# read at runtime from Key Vault via the ACA managed identity (ADR 0004),",
        "# never rendered here.",
        "DSF_MODE=azure",
        f"DSF_PRODUCT={product}",
    ]
    lines.extend(f"{var}={outputs.get(key, '')}" for var, key in _ENDPOINT_MAP)
    return "\n".join(lines) + "\n"


def _render_containerapp(*, app: str, container: str, product: str, image: str, role: str) -> str:
    """Render a single Azure Container Apps descriptor.

    Renders the feature-council (``deploy_council``) runtime. Identity, env, and
    scale are provisioned by ``infra/main.bicep``; this is the declarative record
    reconciled by ``az containerapp update``.
    """
    return (
        "# containerapp.yaml — GENERATED by dsf (render_runtime_bundle).\n"
        f"# App: {app}\n"
        f"# {role} for product '{product}', hosted on Azure Container Apps (ADR 0004).\n"
        "properties:\n"
        "  configuration:\n"
        "    activeRevisionsMode: Single\n"
        "  template:\n"
        "    containers:\n"
        f"      - name: {container}\n"
        f"        image: {image}\n"
        "        env:\n"
        "          - name: DSF_MODE\n"
        "            value: azure\n"
        "          - name: DSF_PRODUCT\n"
        f"            value: {product}\n"
        "    scale:\n"
        "      minReplicas: 1\n"
        "      maxReplicas: 1\n"
    )


def render_runtime_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> RuntimeBundle:
    """Render ``containerapp.yaml`` + ``.env.orchestrator`` for ``manifest``.

    Tolerates a manifest with no Azure outputs yet (endpoints render blank).
    """
    product = manifest.spec.product
    outputs = manifest.azure.outputs if manifest.azure else {}
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    env_path = rdir / ".env.orchestrator"
    app_config_path = rdir / "containerapp.yaml"
    env_path.write_text(_render_env(product, outputs), encoding="utf-8")
    app_config_path.write_text(
        _render_containerapp(
            app=f"dsf-orchestrator-{product}",
            container="orchestrator",
            product=product,
            image=manifest.spec.runtime_image,
            role="Feature-council orchestrator runtime",
        ),
        encoding="utf-8",
    )
    return RuntimeBundle(
        runtime_dir=rdir, app_config_path=app_config_path, env_path=env_path
    )


def _render_sre_onboarding_md(
    *, product: str, resource_group: str, location: str, repo: str
) -> str:
    return (
        f"# Azure SRE Agent onboarding — {product}\n\n"
        "GENERATED by dsf (render_sre_onboarding). Do not edit.\n\n"
        "DSF leverages the **Azure SRE Agent** product instead of a bespoke SRE\n"
        "runtime (ADR 0009). Onboarding is interactive (wizard + OAuth); follow\n"
        "these per-instance steps to stand up the agent for this product.\n\n"
        "## 1. Create the agent\n\n"
        "1. Go to <https://sre.azure.com> and sign in.\n"
        "2. Start **Basics -> Review -> Deploy**.\n"
        f"3. Resource group: `{resource_group}` (region `{location}`); subscription:\n"
        "   the one that owns that resource group.\n"
        f"4. Agent name: `dsf-sre-{product}`. Model provider: Azure OpenAI for EU\n"
        "   data-residency tenants, otherwise the regional default.\n\n"
        "## 2. Connect the product repository\n\n"
        f"On the **Code** card, connect `{repo}` (GitHub, OAuth or PAT).\n\n"
        "## 3. Grant Azure resource access\n\n"
        f"On the **Azure Resources** card, grant the agent Reader on resource group\n"
        f"`{resource_group}`.\n\n"
        "## 4. Keep the squad handoff (fast path)\n\n"
        "The agent files issues/PRs into the repo. Incident issues must carry the\n"
        f"`{HANDOFF_LABEL}` label so the standing coding-squad Ralph watch loop\n"
        "picks them up — that label is already created by the `create_labels`\n"
        "provisioning step.\n\n"
        "## 5. Stamp the incident marker (slow path)\n\n"
        f"Also stamp every incident issue with the `{INCIDENT_LABEL}` label. The\n"
        "feature council's incidents source pulls issues carrying it on its own\n"
        "schedule, so the council now learns from resolved incidents (recurring\n"
        "faults become systemic hardening proposals) alongside production\n"
        f"telemetry. `{INCIDENT_LABEL}` is created by the `create_labels` step.\n"
    )


def render_sre_onboarding(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> SreOnboarding:
    """Render ``sre-onboarding.md`` — the per-product Azure SRE Agent runbook.

    DSF leverages the Azure SRE Agent product (ADR 0009). Onboarding is
    wizard/OAuth-driven, so this renders deterministic guidance scoped to the
    product's resource group, region, and repository rather than deploying a
    custom runtime.
    """
    spec = manifest.spec
    product = spec.product
    rdir = runtime_dir(product, repo_root)
    rdir.mkdir(parents=True, exist_ok=True)
    onboarding_path = rdir / "sre-onboarding.md"
    onboarding_path.write_text(
        _render_sre_onboarding_md(
            product=product,
            resource_group=spec.resource_group(),
            location=spec.location,
            repo=spec.github_repo(),
        ),
        encoding="utf-8",
    )
    return SreOnboarding(runtime_dir=rdir, onboarding_path=onboarding_path)


def _product_from_spec(spec: InstanceSpec) -> Product:
    """Map an instance spec to its runtime :class:`Product` registry entry.

    Observability scopes (``sentry_projects`` / ``grafana_dashboards``) are left
    empty here — they are filled in during observability onboarding —, while
    ``foundryiq_scope`` and ``azure_monitor_scope`` default to the product key
    (the live Application Insights id is filled in during observability
    onboarding).
    """
    return Product(
        key=spec.product,
        github_repo=spec.github_repo(),
        label_taxonomy=spec.label_taxonomy,
        confidence_threshold=spec.confidence_threshold,
        foundryiq_scope=spec.product,
        azure_monitor_scope=spec.product,
    )


def render_product_registration(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> Path:
    """Register the product into ``config/products.json`` (the routing registry).

    Derives a :class:`~dsf.config.registry.Product` from the instance spec and
    upserts it idempotently, so S1 scoping and S6 routing can resolve the product
    to its repo as a byproduct of ``dsf new``. Pure local file IO (no network),
    so it runs in both dry-run and execute. Returns the registry path.
    """
    products_json = (repo_root or _default_repo_root()) / "config" / "products.json"
    return register_product(_product_from_spec(manifest.spec), path=products_json)


__all__ = [
    "RuntimeBundle",
    "SreOnboarding",
    "render_product_registration",
    "render_runtime_bundle",
    "render_sre_onboarding",
    "runtime_dir",
]
