"""Render the per-product squad execution bundle (Ralph + KEDA + exporter).

For an :class:`~dsf.instance.spec.InstanceManifest`, write three Kubernetes
manifests into ``config/instances/<product>.runtime/squad/``:

- ``ralph-deployment.yaml`` -- the Ralph watch loop (``squad watch --execute``)
  with a persistent ``git-notes`` state backend, so per-member ``.squad/`` memory
  survives the ephemeral, scale-to-zero pod.
- ``ralph-scaledobject.yaml`` -- a KEDA ScaledObject scaling the Deployment 0..1
  off the open ``squad:ready`` issue count (the ``metrics-api`` scaler reads the
  exporter).
- ``issue-exporter.yaml`` -- the small exporter Deployment + Service that serves
  the issue count for KEDA.

Secrets (the GitHub App token) are NOT rendered: pods read them from Key Vault via
AKS workload identity (ADR 0012). Image references mirror ``runtime_image`` -- they
are deployment artifacts, not built here.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dsf.contracts.handoff import HANDOFF_LABEL
from dsf.instance.runtime_render import runtime_dir
from dsf.instance.spec import InstanceManifest

RALPH_IMAGE = "ghcr.io/joranbergfeld/dsf-squad-ralph:latest"
EXPORTER_IMAGE = "ghcr.io/joranbergfeld/dsf-issue-exporter:latest"


@dataclass(frozen=True)
class SquadBundle:
    """Paths to the rendered squad manifests for one product."""

    squad_dir: Path
    deployment_path: Path
    scaledobject_path: Path
    exporter_path: Path


def _render_deployment(*, product: str, repo: str) -> str:
    return (
        "# ralph-deployment.yaml -- GENERATED by dsf (render_squad_bundle).\n"
        f"# Ralph watch loop for product '{product}' (ADR 0012).\n"
        "apiVersion: apps/v1\n"
        "kind: Deployment\n"
        "metadata:\n"
        f"  name: ralph-{product}\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  replicas: 0\n"
        "  selector:\n"
        f"    matchLabels: {{app: ralph-{product}}}\n"
        "  template:\n"
        "    metadata:\n"
        f"      labels: {{app: ralph-{product}, azure.workload.identity/use: \"true\"}}\n"
        "    spec:\n"
        "      containers:\n"
        "        - name: ralph\n"
        f"          image: {RALPH_IMAGE}\n"
        "          args:\n"
        "            - squad\n"
        "            - watch\n"
        "            - --execute\n"
        "            - --state-backend\n"
        "            - git-notes\n"
        "            - --label\n"
        f"            - {HANDOFF_LABEL}\n"
        "          env:\n"
        f"            - {{name: SQUAD_REPO, value: {repo}}}\n"
    )


def _render_scaledobject(*, product: str) -> str:
    return (
        "# ralph-scaledobject.yaml -- GENERATED by dsf (render_squad_bundle).\n"
        f"# KEDA scales Ralph 0..1 on the open '{HANDOFF_LABEL}' issue count (ADR 0012).\n"
        "apiVersion: keda.sh/v1alpha1\n"
        "kind: ScaledObject\n"
        "metadata:\n"
        f"  name: ralph-{product}\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  scaleTargetRef:\n"
        f"    name: ralph-{product}\n"
        "  minReplicaCount: 0\n"
        "  maxReplicaCount: 1\n"
        "  triggers:\n"
        "    - type: metrics-api\n"
        "      metadata:\n"
        f"        url: http://issue-exporter.squad-{product}.svc/metrics\n"
        "        valueLocation: count\n"
        "        targetValue: \"1\"\n"
    )


def _render_exporter(*, product: str, repo: str) -> str:
    return (
        "# issue-exporter.yaml -- GENERATED by dsf (render_squad_bundle).\n"
        f"# Serves the open '{HANDOFF_LABEL}' issue count for KEDA (ADR 0012).\n"
        "apiVersion: v1\n"
        "kind: Namespace\n"
        "metadata:\n"
        f"  name: squad-{product}\n"
        "---\n"
        "apiVersion: apps/v1\n"
        "kind: Deployment\n"
        "metadata:\n"
        "  name: issue-exporter\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  replicas: 1\n"
        "  selector:\n"
        "    matchLabels: {app: issue-exporter}\n"
        "  template:\n"
        "    metadata:\n"
        "      labels: {app: issue-exporter, azure.workload.identity/use: \"true\"}\n"
        "    spec:\n"
        "      containers:\n"
        "        - name: exporter\n"
        f"          image: {EXPORTER_IMAGE}\n"
        "          env:\n"
        f"            - {{name: SQUAD_REPO, value: {repo}}}\n"
        f"            - {{name: HANDOFF_LABEL, value: {HANDOFF_LABEL}}}\n"
        "---\n"
        "apiVersion: v1\n"
        "kind: Service\n"
        "metadata:\n"
        "  name: issue-exporter\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  selector: {app: issue-exporter}\n"
        "  ports:\n"
        "    - {port: 80, targetPort: 8080}\n"
    )


def render_squad_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> SquadBundle:
    """Render the Ralph Deployment, KEDA ScaledObject, and exporter for ``manifest``."""
    spec = manifest.spec
    product = spec.product
    repo = spec.github_repo()
    sdir = runtime_dir(product, repo_root) / "squad"
    sdir.mkdir(parents=True, exist_ok=True)
    deployment_path = sdir / "ralph-deployment.yaml"
    scaledobject_path = sdir / "ralph-scaledobject.yaml"
    exporter_path = sdir / "issue-exporter.yaml"
    deployment_path.write_text(
        _render_deployment(product=product, repo=repo), encoding="utf-8"
    )
    scaledobject_path.write_text(
        _render_scaledobject(product=product), encoding="utf-8"
    )
    exporter_path.write_text(
        _render_exporter(product=product, repo=repo), encoding="utf-8"
    )
    return SquadBundle(
        squad_dir=sdir,
        deployment_path=deployment_path,
        scaledobject_path=scaledobject_path,
        exporter_path=exporter_path,
    )


__all__ = ["SquadBundle", "render_squad_bundle"]
