"""Render the per-product squad execution bundle (Ralph + KEDA + exporter).

For an :class:`~dsf.instance.spec.InstanceManifest`, write four Kubernetes
manifests into ``config/instances/<product>.runtime/squad/``:

- ``squad-identity.yaml`` -- the ``squad-<product>`` Namespace, the
  workload-identity ``ServiceAccount`` (annotated with the squad identity's
  client id), and the Key Vault ``SecretProviderClass`` that projects the GitHub
  token (ADR 0012). Applied first so the namespaced objects below resolve.
- ``ralph-deployment.yaml`` -- the Ralph watch loop (``squad watch --execute``)
  with a persistent ``git-notes`` state backend, so per-member ``.squad/`` memory
  survives the ephemeral, scale-to-zero pod.
- ``ralph-scaledobject.yaml`` -- a KEDA ScaledObject scaling the Deployment 0..1
  off the open ``squad:ready`` issue count (the ``metrics-api`` scaler reads the
  exporter).
- ``issue-exporter.yaml`` -- the small exporter Deployment + Service that serves
  the issue count for KEDA.

Both pods run under AKS workload identity: they assume the ``squad-<product>``
ServiceAccount and read ``GITHUB_TOKEN`` from the Key Vault secret the CSI driver
projects (never a static in-cluster secret). The identity client id, Key Vault
name, and tenant id come from the product's Azure deployment outputs; in a
dry-run (no outputs yet) they render blank, like the runtime bundle. Image
references mirror ``runtime_image`` -- they are deployment artifacts, not built
here.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dsf.contracts.handoff import HANDOFF_LABEL
from dsf.instance.runtime_render import runtime_dir
from dsf.instance.spec import InstanceManifest

RALPH_IMAGE = "ghcr.io/joranbergfeld/dsf-squad-ralph:latest"
EXPORTER_IMAGE = "ghcr.io/joranbergfeld/dsf-issue-exporter:latest"

#: Name of the GitHub credential secret in the per-product Key Vault, synced to
#: the in-cluster ``squad-github`` Secret and read as ``GITHUB_TOKEN``.
KV_SECRET_NAME = "github-token"


@dataclass(frozen=True)
class SquadBundle:
    """Paths to the rendered squad manifests for one product."""

    squad_dir: Path
    identity_path: Path
    deployment_path: Path
    scaledobject_path: Path
    exporter_path: Path


def _token_projection(*, product: str) -> str:
    """The shared GITHUB_TOKEN env + Key Vault CSI volume both squad pods use."""
    return (
        "            - name: GITHUB_TOKEN\n"
        "              valueFrom:\n"
        "                secretKeyRef: {name: squad-github, key: token}\n"
        "          volumeMounts:\n"
        "            - {name: secrets-store, mountPath: /mnt/secrets-store, readOnly: true}\n"
        "      volumes:\n"
        "        - name: secrets-store\n"
        "          csi:\n"
        "            driver: secrets-store.csi.k8s.io\n"
        "            readOnly: true\n"
        f"            volumeAttributes: {{secretProviderClass: squad-kv-{product}}}\n"
    )


def _render_identity(
    *, product: str, client_id: str, keyvault_name: str, tenant_id: str
) -> str:
    return (
        "# squad-identity.yaml -- GENERATED by dsf (render_squad_bundle).\n"
        f"# Namespace + workload-identity SA + Key Vault CSI for '{product}' (ADR 0012).\n"
        "apiVersion: v1\n"
        "kind: Namespace\n"
        "metadata:\n"
        f"  name: squad-{product}\n"
        "---\n"
        "apiVersion: v1\n"
        "kind: ServiceAccount\n"
        "metadata:\n"
        f"  name: squad-{product}\n"
        f"  namespace: squad-{product}\n"
        "  annotations:\n"
        f'    azure.workload.identity/client-id: "{client_id}"\n'
        "---\n"
        "apiVersion: secrets-store.csi.x-k8s.io/v1\n"
        "kind: SecretProviderClass\n"
        "metadata:\n"
        f"  name: squad-kv-{product}\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  provider: azure\n"
        "  secretObjects:\n"
        "    - secretName: squad-github\n"
        "      type: Opaque\n"
        "      data:\n"
        f"        - objectName: {KV_SECRET_NAME}\n"
        "          key: token\n"
        "  parameters:\n"
        '    usePodIdentity: "false"\n'
        '    useVMManagedIdentity: "false"\n'
        f'    clientID: "{client_id}"\n'
        f'    keyvaultName: "{keyvault_name}"\n'
        f'    tenantId: "{tenant_id}"\n'
        "    objects: |\n"
        "      array:\n"
        "        - |\n"
        f"          objectName: {KV_SECRET_NAME}\n"
        "          objectType: secret\n"
    )


def _render_deployment(*, product: str, repo: str) -> str:
    return (
        "# ralph-deployment.yaml -- GENERATED by dsf (render_squad_bundle).\n"
        f"# Ralph watch loop for product '{product}' (ADR 0012).\n"
        "apiVersion: apps/v1\n"
        "kind: Deployment\n"
        "metadata:\n"
        f"  name: ralph-{product}\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  replicas: 0\n"
        "  selector:\n"
        f"    matchLabels: {{app: ralph-{product}}}\n"
        "  template:\n"
        "    metadata:\n"
        f'      labels: {{app: ralph-{product}, azure.workload.identity/use: "true"}}\n'
        "    spec:\n"
        f"      serviceAccountName: squad-{product}\n"
        "      containers:\n"
        "        - name: ralph\n"
        f"          image: {RALPH_IMAGE}\n"
        "          args:\n"
        "            - squad\n"
        "            - watch\n"
        "            - --execute\n"
        "            - --state-backend\n"
        "            - git-notes\n"
        "            - --label\n"
        f"            - {HANDOFF_LABEL}\n"
        "          env:\n"
        f"            - {{name: SQUAD_REPO, value: {repo}}}\n"
        + _token_projection(product=product)
    )


def _render_scaledobject(*, product: str) -> str:
    return (
        "# ralph-scaledobject.yaml -- GENERATED by dsf (render_squad_bundle).\n"
        f"# KEDA scales Ralph 0..1 on the open '{HANDOFF_LABEL}' issue count (ADR 0012).\n"
        "apiVersion: keda.sh/v1alpha1\n"
        "kind: ScaledObject\n"
        "metadata:\n"
        f"  name: ralph-{product}\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  scaleTargetRef:\n"
        f"    name: ralph-{product}\n"
        "  minReplicaCount: 0\n"
        "  maxReplicaCount: 1\n"
        "  triggers:\n"
        "    - type: metrics-api\n"
        "      metadata:\n"
        f"        url: http://issue-exporter.squad-{product}.svc/metrics\n"
        "        valueLocation: count\n"
        '        targetValue: "1"\n'
    )


def _render_exporter(*, product: str, repo: str) -> str:
    return (
        "# issue-exporter.yaml -- GENERATED by dsf (render_squad_bundle).\n"
        f"# Serves the open '{HANDOFF_LABEL}' issue count for KEDA (ADR 0012).\n"
        "apiVersion: apps/v1\n"
        "kind: Deployment\n"
        "metadata:\n"
        "  name: issue-exporter\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  replicas: 1\n"
        "  selector:\n"
        "    matchLabels: {app: issue-exporter}\n"
        "  template:\n"
        "    metadata:\n"
        '      labels: {app: issue-exporter, azure.workload.identity/use: "true"}\n'
        "    spec:\n"
        f"      serviceAccountName: squad-{product}\n"
        "      containers:\n"
        "        - name: exporter\n"
        f"          image: {EXPORTER_IMAGE}\n"
        "          env:\n"
        f"            - {{name: SQUAD_REPO, value: {repo}}}\n"
        f"            - {{name: HANDOFF_LABEL, value: {HANDOFF_LABEL}}}\n"
        + _token_projection(product=product)
        + "---\n"
        "apiVersion: v1\n"
        "kind: Service\n"
        "metadata:\n"
        "  name: issue-exporter\n"
        f"  namespace: squad-{product}\n"
        "spec:\n"
        "  selector: {app: issue-exporter}\n"
        "  ports:\n"
        "    - {port: 80, targetPort: 8080}\n"
    )


def render_squad_bundle(
    manifest: InstanceManifest, *, repo_root: Path | None = None
) -> SquadBundle:
    """Render the squad identity, Ralph Deployment, ScaledObject, and exporter."""
    spec = manifest.spec
    product = spec.product
    repo = spec.github_repo()
    outputs = manifest.azure.outputs if manifest.azure else {}
    client_id = outputs.get("squadIdentityClientId", "")
    keyvault_name = outputs.get("keyVaultName", "")
    tenant_id = outputs.get("tenantId", "")
    sdir = runtime_dir(product, repo_root) / "squad"
    sdir.mkdir(parents=True, exist_ok=True)
    identity_path = sdir / "squad-identity.yaml"
    deployment_path = sdir / "ralph-deployment.yaml"
    scaledobject_path = sdir / "ralph-scaledobject.yaml"
    exporter_path = sdir / "issue-exporter.yaml"
    identity_path.write_text(
        _render_identity(
            product=product,
            client_id=client_id,
            keyvault_name=keyvault_name,
            tenant_id=tenant_id,
        ),
        encoding="utf-8",
    )
    deployment_path.write_text(
        _render_deployment(product=product, repo=repo), encoding="utf-8"
    )
    scaledobject_path.write_text(
        _render_scaledobject(product=product), encoding="utf-8"
    )
    exporter_path.write_text(
        _render_exporter(product=product, repo=repo), encoding="utf-8"
    )
    return SquadBundle(
        squad_dir=sdir,
        identity_path=identity_path,
        deployment_path=deployment_path,
        scaledobject_path=scaledobject_path,
        exporter_path=exporter_path,
    )


__all__ = ["SquadBundle", "render_squad_bundle"]
