"""Deterministic Charter -> Spec Kit constitution renderer.

Projects the human-owned :class:`Charter` into the Spec Kit constitution document
(`.specify/memory/constitution.md`) that the ``/speckit.*`` lifecycle reads as its
governing principles. Pure and offline: the same charter always renders the same
constitution. The constitution is a *derived projection* of the charter and
introduces no new intent; the charter stays the single source of truth (ADR 0017).
"""

from __future__ import annotations

from datetime import UTC, date, datetime

from dsf.contracts.charter import Charter

#: Repo-relative path Spec Kit reads the constitution from.
CONSTITUTION_PATH = ".specify/memory/constitution.md"

_SCHEMA_VERSION = 1
_NONE_DECLARED = "- (none declared in the charter)"


def _today() -> date:
    return datetime.now(UTC).date()


def render_constitution(charter: Charter, *, today: date | None = None) -> str:
    """Render ``charter`` as a Spec Kit constitution (markdown).

    ``today`` defaults to the current UTC date and is injectable so tests pin the
    dated footer.
    """
    stamp = (today or _today()).isoformat()

    def bullets(items: list[str]) -> str:
        return "\n".join(f"- {item}" for item in items) if items else _NONE_DECLARED

    glossary = (
        "\n".join(f"- **{term}**: {definition}" for term, definition in charter.glossary.items())
        if charter.glossary
        else "- (no shared vocabulary declared)"
    )
    constraints = (
        charter.constraints.strip()
        or "No additional constraints declared in the charter."
    )

    sections = [
        (
            f"<!-- dsf:constitution schema_version={_SCHEMA_VERSION} "
            f"source_ref={charter.source_ref or 'unknown'} "
            f"source_sha={charter.source_sha or 'unknown'} -->"
        ),
        f"# {charter.product} Constitution",
        (
            "This constitution is a derived projection of the human-owned product "
            "charter (`.dsf/charter.md`). The charter is the single source of truth; "
            "if they ever disagree, the charter wins and this file is re-rendered "
            "from it.\n\n"
            f"**Vision.** {charter.vision.strip()}\n\n"
            f"**Target users.** {charter.target_users.strip()}"
        ),
        "## Core Principles",
        (
            "### I. Charter-Governed (NON-NEGOTIABLE)\n"
            "The product charter is authoritative. Every spec, plan, task, and line "
            "of code must trace back to the charter's vision, goals, and success "
            "metrics. Nothing here may introduce intent the charter does not express."
        ),
        (
            "### II. Goal-Driven Scope\n"
            "Work exists to advance these charter goals:\n"
            + bullets(charter.goals)
        ),
        (
            "### III. Explicit Non-Goals\n"
            "The charter rules the following out of scope; do not build them:\n"
            + bullets(charter.non_goals)
        ),
        (
            "### IV. Measured by Success Metrics\n"
            '"Done and faithful to intent" means moving these charter metrics:\n'
            + bullets(charter.success_metrics)
        ),
        (
            "### V. Shared Vocabulary\n"
            "Use the charter's glossary terms consistently in specs, code, and UI:\n"
            + glossary
        ),
        "## Additional Constraints",
        constraints,
        "## Governance",
        (
            "This constitution supersedes ad-hoc practice for this product. It is "
            "regenerated by `dsf charter implement` whenever the charter changes; "
            "amend the charter (`.dsf/charter.md`), never this file directly. All "
            "specs, plans, and PRs must verify compliance with the principles above."
        ),
        f"**Version**: 1.0.0 | **Ratified**: {stamp} | **Last Amended**: {stamp}",
    ]
    return "\n\n".join(sections) + "\n"


__all__ = ["CONSTITUTION_PATH", "render_constitution"]
